import io
import pandas as pd
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from utils.helpers import format_number, format_currency, format_percent

def generate_docx_report(analysis_bundle: dict) -> bytes:
    """
    Generates a Microsoft Word document (.docx) and returns the document as raw bytes.
    Includes Overview, KPIs, AI Insights (Summary, Findings, Trends, Opportunities, Risks), and Action Recommendations.
    """
    doc = Document()
    
    # Configure margins (1 inch)
    for section in doc.sections:
        section.top_margin = Inches(1.0)
        section.bottom_margin = Inches(1.0)
        section.left_margin = Inches(1.0)
        section.right_margin = Inches(1.0)
        
    # Standard styles configurations
    style_normal = doc.styles['Normal']
    font = style_normal.font
    font.name = 'Calibri'
    font.size = Pt(11)
    font.color.rgb = RGBColor(0x37, 0x41, 0x51) # Gray 700
    
    # Custom Color Palette
    PRIMARY_COLOR = RGBColor(79, 70, 229)    # Indigo #4F46E5
    SECONDARY_COLOR = RGBColor(124, 58, 237) # Violet #7C3AED
    
    # 1. Document Title
    title = doc.add_paragraph()
    title_run = title.add_run("Executive Business Analytics Report")
    title_run.font.name = 'Calibri'
    title_run.font.size = Pt(26)
    title_run.font.bold = True
    title_run.font.color.rgb = PRIMARY_COLOR
    title.alignment = WD_ALIGN_PARAGRAPH.LEFT
    
    # Subtitle
    domain = analysis_bundle.get("domain", "Generic")
    num_rows = analysis_bundle.get("overview", {}).get("num_rows", 0)
    subtitle = doc.add_paragraph()
    sub_run = subtitle.add_run(f"Auto-generated by Business Analyst AI  |  Domain: {domain} Analysis  |  Records: {num_rows:,}")
    sub_run.font.size = Pt(10)
    sub_run.font.italic = True
    sub_run.font.color.rgb = RGBColor(107, 114, 128) # Gray 500
    
    doc.add_paragraph("").paragraph_format.space_after = Pt(12)
    
    # 2. Executive Summary
    h1 = doc.add_heading(level=1)
    h1_run = h1.add_run("1. Executive Summary")
    h1_run.font.color.rgb = SECONDARY_COLOR
    h1_run.font.bold = True
    
    insights = analysis_bundle.get("insights", {})
    exec_sum = insights.get("executive_summary", "No executive summary available.")
    p_sum = doc.add_paragraph(exec_sum)
    p_sum.paragraph_format.line_spacing = 1.15
    p_sum.paragraph_format.space_after = Pt(12)
    
    # 3. Dataset Overview & Health Audit
    h2 = doc.add_heading(level=1)
    h2_run = h2.add_run("2. Dataset Overview & Health Audit")
    h2_run.font.color.rgb = SECONDARY_COLOR
    h2_run.font.bold = True
    
    overview = analysis_bundle.get("overview", {})
    
    # Metadata Overview Table
    meta_table = doc.add_table(rows=1, cols=4)
    meta_table.style = 'Light Shading Accent 1'
    
    meta_headers = ["Total Records", "Total Columns", "Duplicate Rows", "Memory Usage"]
    hdr_cells = meta_table.rows[0].cells
    for i, title_text in enumerate(meta_headers):
        hdr_cells[i].text = title_text
        hdr_cells[i].paragraphs[0].runs[0].font.bold = True
        hdr_cells[i].paragraphs[0].runs[0].font.color.rgb = RGBColor(255, 255, 255)
        hdr_cells[i].paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.CENTER
        
    row_cells = meta_table.add_row().cells
    row_cells[0].text = f"{overview.get('num_rows', 0):,}"
    row_cells[1].text = f"{overview.get('num_columns', 0)}"
    row_cells[2].text = f"{overview.get('duplicate_rows', 0):,}"
    row_cells[3].text = f"{overview.get('memory_usage_mb', 0)} MB"
    
    for cell in row_cells:
        cell.paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.CENTER
        
    doc.add_paragraph("").paragraph_format.space_after = Pt(12)
    
    # Column Structures & Data Quality Audit (Preview)
    h_preview = doc.add_heading(level=2)
    h_preview_run = h_preview.add_run("Column Structures & Data Quality Audit (Preview)")
    h_preview_run.font.color.rgb = SECONDARY_COLOR
    h_preview_run.font.bold = True
    
    quality = analysis_bundle.get("quality_report", {})
    q_table = doc.add_table(rows=1, cols=5)
    q_table.style = 'Light Shading Accent 1'
    
    q_headers = ["Column Name", "Data Type", "Null Count", "Null %", "Outliers (IQR)"]
    hdr_cells = q_table.rows[0].cells
    for i, title_text in enumerate(q_headers):
        hdr_cells[i].text = title_text
        hdr_cells[i].paragraphs[0].runs[0].font.bold = True
        hdr_cells[i].paragraphs[0].runs[0].font.color.rgb = RGBColor(255, 255, 255)
        if i >= 2:
            hdr_cells[i].paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.RIGHT
            
    for col, q in list(quality.items())[:8]:
        row_cells = q_table.add_row().cells
        row_cells[0].text = col
        row_cells[1].text = q["dtype"]
        row_cells[2].text = f"{q['null_count']:,}"
        row_cells[3].text = f"{q['null_percent']}%"
        row_cells[4].text = f"{q['outliers_count']}" if q["is_numeric"] else "N/A"
        
        row_cells[0].paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.LEFT
        row_cells[1].paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.LEFT
        row_cells[2].paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.RIGHT
        row_cells[3].paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.RIGHT
        row_cells[4].paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.RIGHT
        
    doc.add_paragraph("").paragraph_format.space_after = Pt(18)
    
    # 4. Key Performance Indicators (KPIs)
    h3 = doc.add_heading(level=1)
    h3_run = h3.add_run("3. Key Performance Indicators (KPIs)")
    h3_run.font.color.rgb = SECONDARY_COLOR
    h3_run.font.bold = True
    
    kpis = analysis_bundle.get("kpis", {})
    
    # Create Table
    kpi_table = doc.add_table(rows=1, cols=2)
    kpi_table.style = 'Light Shading Accent 1'
    
    hdr_cells = kpi_table.rows[0].cells
    hdr_cells[0].text = 'KPI Metric'
    hdr_cells[1].text = 'Value'
    
    # Style Header
    for cell in hdr_cells:
        cell.paragraphs[0].runs[0].font.bold = True
        cell.paragraphs[0].runs[0].font.color.rgb = RGBColor(255, 255, 255)
        
    for key, info in kpis.items():
        row_cells = kpi_table.add_row().cells
        row_cells[0].text = info["label"]
        
        val = info["value"]
        fmt = info["format"]
        
        # Format metric value
        if fmt == "currency":
            val_str = format_currency(val)
        elif fmt == "percent":
            val_str = format_percent(val)
        elif fmt == "integer":
            val_str = f"{int(val):,}" if not pd.isna(val) else "N/A"
        else:
            val_str = format_number(val)
            
        row_cells[1].text = val_str
        row_cells[1].paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.RIGHT
        
    doc.add_paragraph("").paragraph_format.space_after = Pt(18)
    
    # 5. AI Strategic Insights
    h4 = doc.add_heading(level=1)
    h4_run = h4.add_run("4. AI Strategic Insights")
    h4_run.font.color.rgb = SECONDARY_COLOR
    h4_run.font.bold = True
    
    # Sub-section: Key Findings
    findings = insights.get("key_findings", [])
    if findings:
        sub_h = doc.add_heading(level=2)
        sub_h_run = sub_h.add_run("Core Strategic Findings")
        sub_h_run.font.color.rgb = SECONDARY_COLOR
        sub_h_run.font.bold = True
        for finding in findings:
            p_bullet = doc.add_paragraph(finding, style='List Bullet')
            p_bullet.paragraph_format.space_after = Pt(4)
        doc.add_paragraph("").paragraph_format.space_after = Pt(6)
        
    # Sub-section: Trends & Anomalies
    trends = insights.get("trends_anomalies", [])
    if trends:
        sub_h = doc.add_heading(level=2)
        sub_h_run = sub_h.add_run("Trend & Anomaly Analysis")
        sub_h_run.font.color.rgb = SECONDARY_COLOR
        sub_h_run.font.bold = True
        for trend in trends:
            p_bullet = doc.add_paragraph(trend, style='List Bullet')
            p_bullet.paragraph_format.space_after = Pt(4)
        doc.add_paragraph("").paragraph_format.space_after = Pt(6)
        
    # Sub-section: Opportunities
    opps = insights.get("opportunities", [])
    if opps:
        sub_h = doc.add_heading(level=2)
        sub_h_run = sub_h.add_run("Growth & Optimization Opportunities")
        sub_h_run.font.color.rgb = SECONDARY_COLOR
        sub_h_run.font.bold = True
        for opp in opps:
            p_bullet = doc.add_paragraph(opp, style='List Bullet')
            p_bullet.paragraph_format.space_after = Pt(4)
        doc.add_paragraph("").paragraph_format.space_after = Pt(6)
        
    # Sub-section: Risks
    risks = insights.get("risks", [])
    if risks:
        sub_h = doc.add_heading(level=2)
        sub_h_run = sub_h.add_run("Identified Risks & Pain Points")
        sub_h_run.font.color.rgb = SECONDARY_COLOR
        sub_h_run.font.bold = True
        for risk in risks:
            p_bullet = doc.add_paragraph(risk, style='List Bullet')
            p_bullet.paragraph_format.space_after = Pt(4)
        doc.add_paragraph("").paragraph_format.space_after = Pt(6)
        
    # Page break before recommendations
    doc.add_page_break()
    
    # 6. Strategic Recommendations
    recs = analysis_bundle.get("recommendations", [])
    if recs:
        h5 = doc.add_heading(level=1)
        h5_run = h5.add_run("5. Strategic Action Plan & Recommendations")
        h5_run.font.color.rgb = SECONDARY_COLOR
        h5_run.font.bold = True
        
        for idx, r in enumerate(recs, 1):
            title_text = r.get("title", "Recommendation")
            desc = r.get("description", "")
            priority = r.get("priority", "Medium")
            impact = r.get("impact", "Medium Impact")
            conf = r.get("confidence", 80)
            
            p_rec_title = doc.add_paragraph()
            p_rec_title.paragraph_format.space_before = Pt(12)
            p_rec_title.paragraph_format.space_after = Pt(2)
            
            run_idx = p_rec_title.add_run(f"5.{idx} ")
            run_idx.font.bold = True
            run_idx.font.color.rgb = PRIMARY_COLOR
            
            run_title = p_rec_title.add_run(title_text)
            run_title.font.bold = True
            run_title.font.size = Pt(12)
            
            # Meta line
            p_meta = doc.add_paragraph()
            p_meta.paragraph_format.space_after = Pt(4)
            run_meta = p_meta.add_run(f"Priority: {priority.upper()}  |  Impact: {impact.upper()}  |  Confidence: {conf}%")
            run_meta.font.bold = True
            run_meta.font.size = Pt(9)
            run_meta.font.color.rgb = RGBColor(107, 114, 128)
            
            # Description
            p_desc = doc.add_paragraph(desc)
            p_desc.paragraph_format.line_spacing = 1.15
            p_desc.paragraph_format.space_after = Pt(12)
            
    # Save to buffer
    docx_buffer = io.BytesIO()
    doc.save(docx_buffer)
    docx_bytes = docx_buffer.getvalue()
    docx_buffer.close()
    return docx_bytes
