import io
import pandas as pd
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.pdfgen import canvas
from utils.helpers import format_number, format_currency, format_percent

class NumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas to dynamically compute and write total page counts.
    Creates a clean header/footer on every page.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count):
        self.saveState()
        self.setFont("Helvetica-Bold", 8)
        self.setFillColor(colors.HexColor("#A855F7"))
        
        # Header (Only on page 2 onwards)
        if self._pageNumber > 1:
            self.drawString(54, 750, "BUSINESS ANALYST AI - EXECUTIVE REPORT")
            self.setStrokeColor(colors.HexColor("#E5E7EB"))
            self.setLineWidth(0.5)
            self.line(54, 742, 558, 742)
            
        # Footer
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#6B7280"))
        self.drawString(54, 36, "CONFIDENTIAL - FOR INTERNAL USE ONLY")
        self.drawRightString(558, 36, f"Page {self._pageNumber} of {page_count}")
        self.setStrokeColor(colors.HexColor("#E5E7EB"))
        self.setLineWidth(0.5)
        self.line(54, 48, 558, 48)
        
        self.restoreState()

def generate_pdf_report(analysis_bundle: dict) -> bytes:
    """
    Generates a ReportLab PDF and returns the document as raw bytes.
    Includes Overview, KPIs, AI Insights (Summary, Findings, Trends, Opportunities, Risks), and Action Recommendations.
    """
    pdf_buffer = io.BytesIO()
    
    # 0.75 inch margins
    doc = SimpleDocTemplate(
        pdf_buffer,
        pagesize=letter,
        leftMargin=54,
        rightMargin=54,
        topMargin=54,
        bottomMargin=54
    )
    
    styles = getSampleStyleSheet()
    
    # Custom Palette
    PRIMARY = colors.HexColor("#4F46E5")   # Indigo
    SECONDARY = colors.HexColor("#7C3AED") # Violet
    TEXT_DARK = colors.HexColor("#1F2937") # Slate 800
    BG_LIGHT = colors.HexColor("#F9FAFB")  # Slate 50
    
    # Custom Paragraph Styles
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=24,
        leading=28,
        textColor=PRIMARY,
        spaceAfter=8
    )
    
    subtitle_style = ParagraphStyle(
        'DocSubTitle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=12,
        leading=16,
        textColor=colors.HexColor("#4B5563"),
        spaceAfter=24
    )
    
    h1_style = ParagraphStyle(
        'SectionH1',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=14,
        leading=18,
        textColor=SECONDARY,
        spaceBefore=14,
        spaceAfter=8,
        keepWithNext=True
    )
    
    h2_style = ParagraphStyle(
        'SectionH2',
        parent=styles['Heading2'],
        fontName='Helvetica-Bold',
        fontSize=11,
        leading=15,
        textColor=colors.HexColor("#374151"),
        spaceBefore=10,
        spaceAfter=6,
        keepWithNext=True
    )
    
    body_style = ParagraphStyle(
        'BodyTextDark',
        parent=styles['BodyText'],
        fontName='Helvetica',
        fontSize=10,
        leading=14,
        textColor=TEXT_DARK,
        spaceAfter=8
    )
    
    bullet_style = ParagraphStyle(
        'BulletListDark',
        parent=styles['BodyText'],
        fontName='Helvetica',
        fontSize=9.5,
        leading=13.5,
        textColor=TEXT_DARK,
        leftIndent=15,
        firstLineIndent=-10,
        spaceAfter=5
    )

    story = []
    
    # 1. Document Header / Title
    story.append(Paragraph("Executive Business Analytics Report", title_style))
    domain = analysis_bundle.get("domain", "Generic")
    num_rows = analysis_bundle.get("overview", {}).get("num_rows", 0)
    story.append(Paragraph(f"Auto-generated by Business Analyst AI  |  Domain: {domain} Analysis  |  Records: {num_rows:,}", subtitle_style))
    story.append(Spacer(1, 10))
    
    # 2. Executive Summary Section
    insights = analysis_bundle.get("insights", {})
    exec_sum = insights.get("executive_summary", "No executive summary available.")
    story.append(Paragraph("1. Executive Summary", h1_style))
    story.append(Paragraph(exec_sum, body_style))
    story.append(Spacer(1, 10))
    
    # 3. Dataset Overview & Health Audit Section
    story.append(Paragraph("2. Dataset Overview & Health Audit", h1_style))
    overview = analysis_bundle.get("overview", {})
    
    # Metadata Overview Table
    meta_data = [
        ["Total Records", "Total Columns", "Duplicate Rows", "Memory Usage"],
        [
            f"{overview.get('num_rows', 0):,}",
            f"{overview.get('num_columns', 0)}",
            f"{overview.get('duplicate_rows', 0):,}",
            f"{overview.get('memory_usage_mb', 0)} MB"
        ]
    ]
    meta_table = Table(meta_data, colWidths=[1.75*inch, 1.75*inch, 1.75*inch, 1.75*inch])
    meta_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#E5E7EB")),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor("#374151")),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 9),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white]),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#D1D5DB")),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 10))
    
    # Column Quality Table (Show top 8 columns to fit page nicely)
    story.append(Paragraph("Column Structures & Data Quality Audit (Preview)", h2_style))
    quality = analysis_bundle.get("quality_report", {})
    q_data = [["Column Name", "Data Type", "Null Count", "Null %", "Outliers (IQR)"]]
    
    # Limit to top 8 columns to prevent page overflow
    for col, q in list(quality.items())[:8]:
        q_data.append([
            col,
            q["dtype"],
            f"{q['null_count']:,}",
            f"{q['null_percent']}%",
            f"{q['outliers_count']}" if q["is_numeric"] else "N/A"
        ])
    
    q_table = Table(q_data, colWidths=[2.0*inch, 1.25*inch, 1.25*inch, 1.25*inch, 1.25*inch])
    q_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#4B5563")),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 8.5),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('ALIGN', (2, 0), (-1, -1), 'RIGHT'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, BG_LIGHT]),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#E5E7EB")),
    ]))
    story.append(q_table)
    
    # Page Break for KPIs and Insights
    story.append(PageBreak())
    
    # 4. KPI Dashboard Section
    story.append(Paragraph("3. Key Performance Indicators (KPIs)", h1_style))
    kpis = analysis_bundle.get("kpis", {})
    
    kpi_data = [["KPI Metric", "Calculated Value"]]
    for key, info in kpis.items():
        val = info["value"]
        fmt = info["format"]
        
        if fmt == "currency":
            val_str = format_currency(val)
        elif fmt == "percent":
            val_str = format_percent(val)
        elif fmt == "integer":
            val_str = f"{int(val):,}" if not pd.isna(val) else "N/A"
        else:
            val_str = format_number(val)
            
        kpi_data.append([info["label"], val_str])
        
    kpi_table = Table(kpi_data, colWidths=[4.0*inch, 3.0*inch])
    kpi_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (1, 0), PRIMARY),
        ('TEXTCOLOR', (0, 0), (1, 0), colors.white),
        ('FONTNAME', (0, 0), (1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (1, 0), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, BG_LIGHT]),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#E5E7EB")),
        ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 1), (-1, -1), 9),
        ('ALIGN', (1, 0), (1, -1), 'RIGHT'),
    ]))
    story.append(kpi_table)
    story.append(Spacer(1, 15))
    
    # 5. AI Strategic Insights Section
    story.append(Paragraph("4. AI Strategic Insights", h1_style))
    
    # Sub-section: Key Findings
    findings = insights.get("key_findings", [])
    if findings:
        story.append(Paragraph("Core Strategic Findings", h2_style))
        for finding in findings:
            story.append(Paragraph(f"• {finding}", bullet_style))
        story.append(Spacer(1, 8))
        
    # Sub-section: Trends & Anomalies
    trends = insights.get("trends_anomalies", [])
    if trends:
        story.append(Paragraph("Trend & Anomaly Analysis", h2_style))
        for trend in trends:
            story.append(Paragraph(f"• {trend}", bullet_style))
        story.append(Spacer(1, 8))

    # Sub-section: Opportunities
    opps = insights.get("opportunities", [])
    if opps:
        story.append(Paragraph("Growth & Optimization Opportunities", h2_style))
        for opp in opps:
            story.append(Paragraph(f"• {opp}", bullet_style))
        story.append(Spacer(1, 8))

    # Sub-section: Risks
    risks = insights.get("risks", [])
    if risks:
        story.append(Paragraph("Identified Risks & Pain Points", h2_style))
        for risk in risks:
            story.append(Paragraph(f"• {risk}", bullet_style))
        story.append(Spacer(1, 8))
        
    # Page Break for Recommendations
    story.append(PageBreak())
    
    # 6. Actionable Recommendations Section
    story.append(Paragraph("5. Strategic Action Plan & Recommendations", h1_style))
    recs = analysis_bundle.get("recommendations", [])
    if recs:
        for r in recs:
            title = r.get("title", "Recommendation")
            desc = r.get("description", "")
            priority = r.get("priority", "Medium")
            impact = r.get("impact", "Medium Impact")
            conf = r.get("confidence", 80)
            
            p_color = "#3B82F6"
            if priority.upper() == "CRITICAL":
                p_color = "#EF4444"
            elif priority.upper() == "HIGH":
                p_color = "#F59E0B"
            elif priority.upper() == "LOW":
                p_color = "#10B981"
                
            rec_story = []
            rec_title_para = Paragraph(f"<b>{title}</b>", ParagraphStyle('RecT', parent=body_style, fontSize=11, fontName='Helvetica-Bold'))
            rec_meta_para = Paragraph(
                f"<font color='{p_color}'><b>PRIORITY: {priority.upper()}</b></font>  |  "
                f"<b>IMPACT: {impact.upper()}</b>  |  "
                f"<b>CONFIDENCE: {conf}%</b>", 
                ParagraphStyle('RecM', parent=body_style, fontSize=8, textColor=colors.HexColor("#6B7280"))
            )
            rec_desc_para = Paragraph(desc, ParagraphStyle('RecD', parent=body_style, fontSize=9.5, leading=13))
            
            rec_story.append(rec_title_para)
            rec_story.append(rec_meta_para)
            rec_story.append(rec_desc_para)
            rec_story.append(Spacer(1, 4))
            
            # Wrap recommendation card in a 7.0-inch width table
            rec_table = Table([[rec_story]], colWidths=[7.0*inch])
            rec_table.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,-1), BG_LIGHT),
                ('BOX', (0,0), (-1,-1), 1, colors.HexColor("#E5E7EB")),
                ('LEFTPADDING', (0,0), (-1,-1), 12),
                ('RIGHTPADDING', (0,0), (-1,-1), 12),
                ('TOPPADDING', (0,0), (-1,-1), 8),
                ('BOTTOMPADDING', (0,0), (-1,-1), 8),
            ]))
            
            story.append(KeepTogether([rec_table, Spacer(1, 10)]))
            
    # Build Document using NumberedCanvas
    doc.build(story, canvasmaker=NumberedCanvas)
    
    pdf_bytes = pdf_buffer.getvalue()
    pdf_buffer.close()
    return pdf_bytes
